/**
 * Seed Script — Run once to create the admin user and sample astrologers/products
 * Usage: node src/seed.js
 */
import 'dotenv/config';
import mongoose from 'mongoose';
import User from './models/user.model.js';
import Astrologer from './models/astrologer.model.js';
import Admin from './models/admin.model.js';
import Product from './models/product.model.js';
import SystemSettings from './models/systemSettings.model.js';

const MONGO_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/jyotishlink';

async function seed() {
  await mongoose.connect(MONGO_URI);
  console.log('✅ Connected to MongoDB');

  // ── Admin User ──────────────────────────────
  const adminEmail = 'admin@jyotishlink.com';
  let adminUser = await Admin.findOne({ email: adminEmail });
  if (!adminUser) {
    adminUser = await Admin.create({
      name: 'Super Admin',
      phone: '0000000000',
      email: adminEmail,
      password: 'admin@123',
    });
    console.log('✅ Admin user created → email: admin@jyotishlink.com | password: admin@123');
  } else {
    console.log('ℹ️  Admin user already exists');
  }

  // ── Sample Astrologers ──────────────────────
  const astrologerData = [
    { name: 'Pandit Ramesh Sharma', skills: ['Vedic', 'Numerology'], languages: ['Hindi', 'English'], experience: 15, rating: 4.9, about: 'Expert in Vedic astrology with 15 years of experience.', pricing: { chat: 20, audioCall: 30, videoCall: 50 } },
    { name: 'Priya Devi', skills: ['Tarot', 'Vastu'], languages: ['Hindi', 'Tamil'], experience: 8, rating: 4.7, about: 'Specialized in Tarot reading and Vastu Shastra.', pricing: { chat: 15, audioCall: 25, videoCall: 40 } },
    { name: 'Astro Vijay Kumar', skills: ['Kundli', 'Palmistry'], languages: ['Hindi', 'English', 'Gujarati'], experience: 12, rating: 4.8, about: 'Master in Kundli analysis and palmistry.', pricing: { chat: 18, audioCall: 28, videoCall: 45 } },
    { name: 'Dr. Meena Joshi', skills: ['Horoscope', 'Numerology', 'Vedic'], languages: ['Hindi', 'Marathi', 'English'], experience: 20, rating: 5.0, about: 'PhD in Vedic Astrology. Expert in horoscope prediction.', pricing: { chat: 25, audioCall: 40, videoCall: 60 } },
    { name: 'Guru Arjun Nair', skills: ['Pandit', 'Vedic Rituals', 'Pooja'], languages: ['Malayalam', 'Hindi', 'English'], experience: 18, rating: 4.9, about: 'Expert pandit for all types of poojas and rituals.', pricing: { chat: 10, audioCall: 20, videoCall: 35 } },
  ];

  for (const data of astrologerData) {
    const existing = await Astrologer.findOne({ name: data.name });
    if (!existing) {
      await Astrologer.create({
        ...data,
        phone: `99${Math.floor(10000000 + Math.random() * 90000000)}`,
        password: 'astro@123',
        categories: data.skills,
        isVerified: true,
        approvalStatus: 'approved',
        onlineStatus: Math.random() > 0.5 ? 'online' : 'offline',
        orders: `${Math.floor(Math.random() * 5)}k+`,
      });
      console.log(`✅ Astrologer created: ${data.name}`);
    }
  }

  // ── Sample Products ─────────────────────────
  const products = [
    { name: 'Crystal Rudraksha Mala', price: 999, description: '108 bead Rudraksha mala for meditation and spiritual protection.', category: 'Spiritual', image: 'https://placehold.co/300x300/orange/white?text=Rudraksha', inStock: true },
    { name: 'Energized Shree Yantra', price: 1499, description: 'Copper Shree Yantra energized by expert priests for prosperity.', category: 'Yantra', image: 'https://placehold.co/300x300/orange/white?text=Yantra', inStock: true },
    { name: 'Gemstone Kit (Navratna)', price: 2499, description: 'Complete set of 9 gemstones for all planets.', category: 'Gemstone', image: 'https://placehold.co/300x300/orange/white?text=Gems', inStock: true },
    { name: 'Vastu Compass', price: 599, description: 'Professional Vastu compass for directional analysis.', category: 'Vastu', image: 'https://placehold.co/300x300/orange/white?text=Compass', inStock: true },
    { name: 'Kundli Report (Detailed)', price: 299, description: 'Comprehensive 40-page Kundli report generated by expert astrologers.', category: 'Report', image: 'https://placehold.co/300x300/orange/white?text=Kundli', inStock: true },
    { name: 'Pooja Kit (Satyanarayan)', price: 799, description: 'Complete kit for Satyanarayan Pooja with all materials.', category: 'Pooja', image: 'https://placehold.co/300x300/orange/white?text=Pooja', inStock: true },
  ];

  const productCount = await Product.countDocuments();
  if (productCount === 0) {
    await Product.insertMany(products);
    console.log(`✅ ${products.length} products created`);
  } else {
    console.log('ℹ️  Products already seeded');
  }

  // ── System Settings ─────────────────────────
  const settingsCount = await SystemSettings.countDocuments();
  if (settingsCount === 0) {
    await SystemSettings.create({});
    console.log('✅ Default system settings created');
  }

  console.log('\n🎉 Seeding complete!');
  console.log('─────────────────────────────');
  console.log('Admin Login:');
  console.log('  Email:    admin@jyotishlink.com');
  console.log('  Password: admin@123');
  console.log('─────────────────────────────');
  process.exit(0);
}

seed().catch((err) => {
  console.error('Seed error:', err);
  process.exit(1);
});
